/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  PERIODIC_VIEW: () => PERIODIC_VIEW,
  PeriodicView: () => PeriodicView,
  default: () => MyPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");

// periodicTable.json
var periodicTable_default = [
  {
    atomicMass: 1.008,
    atomicRadius: "120",
    block: "s",
    boil: 20.271,
    category: "diatomic nonmetal",
    density: 0.08988,
    electronConfig: "1s1",
    group: 1,
    melt: 13.99,
    name: "Hydrogen",
    number: 1,
    oxidationStates: "+1, -1",
    period: 1,
    phase: "Gas",
    symbol: "H"
  },
  {
    atomicMass: 4.0026022,
    atomicRadius: "140",
    block: "s",
    boil: 4.222,
    category: "noble gas",
    density: 0.1786,
    electronConfig: "1s2",
    group: 18,
    melt: 0.95,
    name: "Helium",
    number: 2,
    oxidationStates: "0",
    period: 1,
    phase: "Gas",
    symbol: "He"
  },
  {
    atomicMass: 6.94,
    atomicRadius: "182",
    block: "s",
    boil: 1603,
    category: "alkali metal",
    density: 0.534,
    electronConfig: "1s2 2s1",
    group: 1,
    melt: 453.65,
    name: "Lithium",
    number: 3,
    oxidationStates: "+1",
    period: 2,
    phase: "Solid",
    symbol: "Li"
  },
  {
    atomicMass: 9.01218315,
    atomicRadius: "153",
    block: "s",
    boil: 2742,
    category: "alkaline earth metal",
    density: 1.85,
    electronConfig: "1s2 2s2",
    group: 2,
    melt: 1560,
    name: "Beryllium",
    number: 4,
    oxidationStates: "+2",
    period: 2,
    phase: "Solid",
    symbol: "Be"
  },
  {
    atomicMass: 10.81,
    atomicRadius: "192",
    block: "p",
    boil: 4200,
    category: "metalloid",
    density: 2.08,
    electronConfig: "1s2 2s2 2p1",
    group: 13,
    melt: 2349,
    name: "Boron",
    number: 5,
    oxidationStates: "+3",
    period: 2,
    phase: "Solid",
    symbol: "B"
  },
  {
    atomicMass: 12.011,
    atomicRadius: "170",
    block: "p",
    boil: 4200,
    category: "polyatomic nonmetal",
    density: 1.821,
    electronConfig: "1s2 2s2 2p2",
    group: 14,
    melt: 2349,
    name: "Carbon",
    number: 6,
    oxidationStates: "+4, +2, -4",
    period: 2,
    phase: "Solid",
    symbol: "C"
  },
  {
    atomicMass: 14.007,
    atomicRadius: "155",
    block: "p",
    boil: 77.355,
    category: "diatomic nonmetal",
    density: 1.251,
    electronConfig: "1s2 2s2 2p3",
    group: 15,
    melt: 63.15,
    name: "Nitrogen",
    number: 7,
    oxidationStates: "+5, +4, +3, +2, +1, -1, -2, -3",
    period: 2,
    phase: "Gas",
    symbol: "N"
  },
  {
    atomicMass: 15.999,
    atomicRadius: "152",
    block: "p",
    boil: 90.188,
    category: "diatomic nonmetal",
    density: 1.429,
    electronConfig: "1s2 2s2 2p4",
    group: 16,
    melt: 54.36,
    name: "Oxygen",
    number: 8,
    oxidationStates: "-2",
    period: 2,
    phase: "Gas",
    symbol: "O"
  },
  {
    atomicMass: 18.9984031636,
    atomicRadius: "135",
    block: "p",
    boil: 85.03,
    category: "diatomic nonmetal",
    density: 1.696,
    electronConfig: "1s2 2s2 2p5",
    group: 17,
    melt: 53.48,
    name: "Fluorine",
    number: 9,
    oxidationStates: "-1",
    period: 2,
    phase: "Gas",
    symbol: "F"
  },
  {
    atomicMass: 20.17976,
    atomicRadius: "154",
    block: "p",
    boil: 27.104,
    category: "noble gas",
    density: 0.9002,
    electronConfig: "1s2 2s2 2p6",
    group: 18,
    melt: 24.56,
    name: "Neon",
    number: 10,
    oxidationStates: "0",
    period: 2,
    phase: "Gas",
    symbol: "Ne"
  },
  {
    atomicMass: 22.989769282,
    atomicRadius: "227",
    block: "s",
    boil: 1156.09,
    category: "alkali metal",
    density: 0.968,
    electronConfig: "1s2 2s2 2p6 3s1",
    group: 1,
    melt: 370.944,
    name: "Sodium",
    number: 11,
    oxidationStates: "+1",
    period: 3,
    phase: "Solid",
    symbol: "Na"
  },
  {
    atomicMass: 24.305,
    atomicRadius: "173",
    block: "s",
    boil: 1363,
    category: "alkaline earth metal",
    density: 1.738,
    electronConfig: "1s2 2s2 2p6 3s2",
    group: 2,
    melt: 923,
    name: "Magnesium",
    number: 12,
    oxidationStates: "+2",
    period: 3,
    phase: "Solid",
    symbol: "Mg"
  },
  {
    atomicMass: 26.98153857,
    atomicRadius: "184",
    block: "p",
    boil: 2743,
    category: "post-transition metal",
    density: 2.7,
    electronConfig: "1s2 2s2 2p6 3s2 3p1",
    group: 13,
    melt: 933.47,
    name: "Aluminium",
    number: 13,
    oxidationStates: "+3",
    period: 3,
    phase: "Solid",
    symbol: "Al"
  },
  {
    atomicMass: 28.085,
    atomicRadius: "210",
    block: "p",
    boil: 3538,
    category: "metalloid",
    density: 2.329,
    electronConfig: "1s2 2s2 2p6 3s2 3p2",
    group: 14,
    melt: 1687,
    name: "Silicon",
    number: 14,
    oxidationStates: "+4, +2, -4",
    period: 3,
    phase: "Solid",
    symbol: "Si"
  },
  {
    atomicMass: 30.9737619985,
    atomicRadius: "180",
    block: "p",
    boil: 3538,
    category: "polyatomic nonmetal",
    density: 1.823,
    electronConfig: "1s2 2s2 2p6 3s2 3p3",
    group: 15,
    melt: 1687,
    name: "Phosphorus",
    number: 15,
    oxidationStates: "+5, +3, -3",
    period: 3,
    phase: "Solid",
    symbol: "P"
  },
  {
    atomicMass: 32.06,
    atomicRadius: "180",
    block: "p",
    boil: 717.8,
    category: "polyatomic nonmetal",
    density: 2.07,
    electronConfig: "1s2 2s2 2p6 3s2 3p4",
    group: 16,
    melt: 388.36,
    name: "Sulfur",
    number: 16,
    oxidationStates: "+6, +4, -2",
    period: 3,
    phase: "Solid",
    symbol: "S"
  },
  {
    atomicMass: 35.45,
    atomicRadius: "175",
    block: "p",
    boil: 239.11,
    category: "diatomic nonmetal",
    density: 3.2,
    electronConfig: "1s2 2s2 2p6 3s2 3p5",
    group: 17,
    melt: 171.6,
    name: "Chlorine",
    number: 17,
    oxidationStates: "+7, +5, +1, -1",
    period: 3,
    phase: "Gas",
    symbol: "Cl"
  },
  {
    atomicMass: 39.9481,
    atomicRadius: "188",
    block: "p",
    boil: 87.302,
    category: "noble gas",
    density: 1.784,
    electronConfig: "1s2 2s2 2p6 3s2 3p6",
    group: 18,
    melt: 83.81,
    name: "Argon",
    number: 18,
    oxidationStates: "0",
    period: 3,
    phase: "Gas",
    symbol: "Ar"
  },
  {
    atomicMass: 39.09831,
    atomicRadius: "275",
    block: "s",
    boil: 1032,
    category: "alkali metal",
    density: 0.862,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s1",
    group: 1,
    melt: 336.7,
    name: "Potassium",
    number: 19,
    oxidationStates: "+1",
    period: 4,
    phase: "Solid",
    symbol: "K"
  },
  {
    atomicMass: 40.0784,
    atomicRadius: "231",
    block: "s",
    boil: 1757,
    category: "alkaline earth metal",
    density: 1.55,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2",
    group: 2,
    melt: 1115,
    name: "Calcium",
    number: 20,
    oxidationStates: "+2",
    period: 4,
    phase: "Solid",
    symbol: "Ca"
  },
  {
    atomicMass: 44.9559085,
    atomicRadius: "211",
    block: "d",
    boil: 3109,
    category: "transition metal",
    density: 2.985,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d1",
    group: 3,
    melt: 1814,
    name: "Scandium",
    number: 21,
    oxidationStates: "+3",
    period: 4,
    phase: "Solid",
    symbol: "Sc"
  },
  {
    atomicMass: 47.8671,
    atomicRadius: "187",
    block: "d",
    boil: 3560,
    category: "transition metal",
    density: 4.506,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d2",
    group: 4,
    melt: 1941,
    name: "Titanium",
    number: 22,
    oxidationStates: "+4, +3, +2",
    period: 4,
    phase: "Solid",
    symbol: "Ti"
  },
  {
    atomicMass: 50.94151,
    atomicRadius: "179",
    block: "d",
    boil: 3680,
    category: "transition metal",
    density: 6,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d3",
    group: 5,
    melt: 2183,
    name: "Vanadium",
    number: 23,
    oxidationStates: "+5, +4, +3, +2",
    period: 4,
    phase: "Solid",
    symbol: "V"
  },
  {
    atomicMass: 51.99616,
    atomicRadius: "189",
    block: "d",
    boil: 2944,
    category: "transition metal",
    density: 7.19,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s1 3d5",
    group: 6,
    melt: 2180,
    name: "Chromium",
    number: 24,
    oxidationStates: "+6, +3, +2",
    period: 4,
    phase: "Solid",
    symbol: "Cr"
  },
  {
    atomicMass: 54.9380443,
    atomicRadius: "197",
    block: "d",
    boil: 2334,
    category: "transition metal",
    density: 7.21,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d5",
    group: 7,
    melt: 1519,
    name: "Manganese",
    number: 25,
    oxidationStates: "+7, +4, +3, +2",
    period: 4,
    phase: "Solid",
    symbol: "Mn"
  },
  {
    atomicMass: 55.8452,
    atomicRadius: "194",
    block: "d",
    boil: 3134,
    category: "transition metal",
    density: 7.874,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d6",
    group: 8,
    melt: 1811,
    name: "Iron",
    number: 26,
    oxidationStates: "+3, +2",
    period: 4,
    phase: "Solid",
    symbol: "Fe"
  },
  {
    atomicMass: 58.9331944,
    atomicRadius: "192",
    block: "d",
    boil: 3200,
    category: "transition metal",
    density: 8.9,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d7",
    group: 9,
    melt: 1768,
    name: "Cobalt",
    number: 27,
    oxidationStates: "+3, +2",
    period: 4,
    phase: "Solid",
    symbol: "Co"
  },
  {
    atomicMass: 58.69344,
    atomicRadius: "163",
    block: "d",
    boil: 3003,
    category: "transition metal",
    density: 8.908,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d8",
    group: 10,
    melt: 1728,
    name: "Nickel",
    number: 28,
    oxidationStates: "+3, +2",
    period: 4,
    phase: "Solid",
    symbol: "Ni"
  },
  {
    atomicMass: 63.5463,
    atomicRadius: "140",
    block: "d",
    boil: 2835,
    category: "transition metal",
    density: 8.96,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s1 3d10",
    group: 11,
    melt: 1357.77,
    name: "Copper",
    number: 29,
    oxidationStates: "+2, +1",
    period: 4,
    phase: "Solid",
    symbol: "Cu"
  },
  {
    atomicMass: 65.382,
    atomicRadius: "139",
    block: "d",
    boil: 1180,
    category: "transition metal",
    density: 7.14,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10",
    group: 12,
    melt: 692.68,
    name: "Zinc",
    number: 30,
    oxidationStates: "+2",
    period: 4,
    phase: "Solid",
    symbol: "Zn"
  },
  {
    atomicMass: 69.7231,
    atomicRadius: "187",
    block: "p",
    boil: 2673,
    category: "post-transition metal",
    density: 5.91,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p1",
    group: 13,
    melt: 302.9146,
    name: "Gallium",
    number: 31,
    oxidationStates: "+3",
    period: 4,
    phase: "Solid",
    symbol: "Ga"
  },
  {
    atomicMass: 72.6308,
    atomicRadius: "211",
    block: "p",
    boil: 3106,
    category: "metalloid",
    density: 5.323,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p2",
    group: 14,
    melt: 1211.4,
    name: "Germanium",
    number: 32,
    oxidationStates: "+4, +2",
    period: 4,
    phase: "Solid",
    symbol: "Ge"
  },
  {
    atomicMass: 74.9215956,
    atomicRadius: "185",
    block: "p",
    boil: 3106,
    category: "metalloid",
    density: 5.727,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p3",
    group: 15,
    melt: 1211.4,
    name: "Arsenic",
    number: 33,
    oxidationStates: "+5, +3, -3",
    period: 4,
    phase: "Solid",
    symbol: "As"
  },
  {
    atomicMass: 78.9718,
    atomicRadius: "190",
    block: "p",
    boil: 958,
    category: "polyatomic nonmetal",
    density: 4.81,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p4",
    group: 16,
    melt: 494,
    name: "Selenium",
    number: 34,
    oxidationStates: "+6, +4, -2",
    period: 4,
    phase: "Solid",
    symbol: "Se"
  },
  {
    atomicMass: 79.904,
    atomicRadius: "183",
    block: "p",
    boil: 332,
    category: "diatomic nonmetal",
    density: 3.1028,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p5",
    group: 17,
    melt: 265.8,
    name: "Bromine",
    number: 35,
    oxidationStates: "+5, +1, -1",
    period: 4,
    phase: "Liquid",
    symbol: "Br"
  },
  {
    atomicMass: 83.7982,
    atomicRadius: "202",
    block: "p",
    boil: 119.93,
    category: "noble gas",
    density: 3.749,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6",
    group: 18,
    melt: 115.78,
    name: "Krypton",
    number: 36,
    oxidationStates: "0",
    period: 4,
    phase: "Gas",
    symbol: "Kr"
  },
  {
    atomicMass: 85.46783,
    atomicRadius: "303",
    block: "s",
    boil: 961,
    category: "alkali metal",
    density: 1.532,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s1",
    group: 1,
    melt: 312.45,
    name: "Rubidium",
    number: 37,
    oxidationStates: "+1",
    period: 5,
    phase: "Solid",
    symbol: "Rb"
  },
  {
    atomicMass: 87.621,
    atomicRadius: "249",
    block: "s",
    boil: 1650,
    category: "alkaline earth metal",
    density: 2.64,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2",
    group: 2,
    melt: 1050,
    name: "Strontium",
    number: 38,
    oxidationStates: "+2",
    period: 5,
    phase: "Solid",
    symbol: "Sr"
  },
  {
    atomicMass: 88.905842,
    atomicRadius: "219",
    block: "d",
    boil: 3203,
    category: "transition metal",
    density: 4.472,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d1",
    group: 3,
    melt: 1799,
    name: "Yttrium",
    number: 39,
    oxidationStates: "+3",
    period: 5,
    phase: "Solid",
    symbol: "Y"
  },
  {
    atomicMass: 91.2242,
    atomicRadius: "186",
    block: "d",
    boil: 4650,
    category: "transition metal",
    density: 6.52,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d2",
    group: 4,
    melt: 2128,
    name: "Zirconium",
    number: 40,
    oxidationStates: "+4",
    period: 5,
    phase: "Solid",
    symbol: "Zr"
  },
  {
    atomicMass: 92.906372,
    atomicRadius: "207",
    block: "d",
    boil: 5017,
    category: "transition metal",
    density: 8.57,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s1 4d4",
    group: 5,
    melt: 2750,
    name: "Niobium",
    number: 41,
    oxidationStates: "+5, +3",
    period: 5,
    phase: "Solid",
    symbol: "Nb"
  },
  {
    atomicMass: 95.951,
    atomicRadius: "209",
    block: "d",
    boil: 4912,
    category: "transition metal",
    density: 10.28,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s1 4d5",
    group: 6,
    melt: 2896,
    name: "Molybdenum",
    number: 42,
    oxidationStates: "+6",
    period: 5,
    phase: "Solid",
    symbol: "Mo"
  },
  {
    atomicMass: 98,
    atomicRadius: "209",
    block: "d",
    boil: 4538,
    category: "transition metal",
    density: 11,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d5",
    group: 7,
    melt: 2430,
    name: "Technetium",
    number: 43,
    oxidationStates: "+7, +6, +4",
    period: 5,
    phase: "Solid",
    symbol: "Tc"
  },
  {
    atomicMass: 101.072,
    atomicRadius: "207",
    block: "d",
    boil: 4423,
    category: "transition metal",
    density: 12.45,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s1 4d7",
    group: 8,
    melt: 2607,
    name: "Ruthenium",
    number: 44,
    oxidationStates: "+3",
    period: 5,
    phase: "Solid",
    symbol: "Ru"
  },
  {
    atomicMass: 102.905502,
    atomicRadius: "195",
    block: "d",
    boil: 3968,
    category: "transition metal",
    density: 12.41,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s1 4d8",
    group: 9,
    melt: 2237,
    name: "Rhodium",
    number: 45,
    oxidationStates: "+3",
    period: 5,
    phase: "Solid",
    symbol: "Rh"
  },
  {
    atomicMass: 106.421,
    atomicRadius: "202",
    block: "d",
    boil: 3236,
    category: "transition metal",
    density: 12.023,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 4d10",
    group: 10,
    melt: 1828.05,
    name: "Palladium",
    number: 46,
    oxidationStates: "+3, +2",
    period: 5,
    phase: "Solid",
    symbol: "Pd"
  },
  {
    atomicMass: 107.86822,
    atomicRadius: "172",
    block: "d",
    boil: 2435,
    category: "transition metal",
    density: 10.49,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s1 4d10",
    group: 11,
    melt: 1234.93,
    name: "Silver",
    number: 47,
    oxidationStates: "+1",
    period: 5,
    phase: "Solid",
    symbol: "Ag"
  },
  {
    atomicMass: 112.4144,
    atomicRadius: "158",
    block: "d",
    boil: 1040,
    category: "transition metal",
    density: 8.65,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10",
    group: 12,
    melt: 594.22,
    name: "Cadmium",
    number: 48,
    oxidationStates: "+2",
    period: 5,
    phase: "Solid",
    symbol: "Cd"
  },
  {
    atomicMass: 114.8181,
    atomicRadius: "193",
    block: "p",
    boil: 2345,
    category: "post-transition metal",
    density: 7.31,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p1",
    group: 13,
    melt: 429.7485,
    name: "Indium",
    number: 49,
    oxidationStates: "+3",
    period: 5,
    phase: "Solid",
    symbol: "In"
  },
  {
    atomicMass: 118.7107,
    atomicRadius: "217",
    block: "p",
    boil: 2875,
    category: "post-transition metal",
    density: 7.365,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p2",
    group: 14,
    melt: 505.08,
    name: "Tin",
    number: 50,
    oxidationStates: "+4, +2",
    period: 5,
    phase: "Solid",
    symbol: "Sn"
  },
  {
    atomicMass: 121.7601,
    atomicRadius: "206",
    block: "p",
    boil: 1908,
    category: "metalloid",
    density: 6.697,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p3",
    group: 15,
    melt: 903.78,
    name: "Antimony",
    number: 51,
    oxidationStates: "+5, +3, -3",
    period: 5,
    phase: "Solid",
    symbol: "Sb"
  },
  {
    atomicMass: 127.603,
    atomicRadius: "206",
    block: "p",
    boil: 1261,
    category: "metalloid",
    density: 6.24,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p4",
    group: 16,
    melt: 722.66,
    name: "Tellurium",
    number: 52,
    oxidationStates: "+6, +4, -2",
    period: 5,
    phase: "Solid",
    symbol: "Te"
  },
  {
    atomicMass: 126.904473,
    atomicRadius: "198",
    block: "p",
    boil: 457.4,
    category: "diatomic nonmetal",
    density: 4.933,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p5",
    group: 17,
    melt: 386.85,
    name: "Iodine",
    number: 53,
    oxidationStates: "+7, +5, +1, -1",
    period: 5,
    phase: "Solid",
    symbol: "I"
  },
  {
    atomicMass: 131.2936,
    atomicRadius: "216",
    block: "p",
    boil: 165.051,
    category: "noble gas",
    density: 5.894,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6",
    group: 18,
    melt: 161.4,
    name: "Xenon",
    number: 54,
    oxidationStates: "0",
    period: 5,
    phase: "Gas",
    symbol: "Xe"
  },
  {
    atomicMass: 132.905451966,
    atomicRadius: "343",
    block: "s",
    boil: 944,
    category: "alkali metal",
    density: 1.93,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s1",
    group: 1,
    melt: 301.7,
    name: "Cesium",
    number: 55,
    oxidationStates: "+1",
    period: 6,
    phase: "Solid",
    symbol: "Cs"
  },
  {
    atomicMass: 137.3277,
    atomicRadius: "268",
    block: "s",
    boil: 2118,
    category: "alkaline earth metal",
    density: 3.51,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2",
    group: 2,
    melt: 1e3,
    name: "Barium",
    number: 56,
    oxidationStates: "+2",
    period: 6,
    phase: "Solid",
    symbol: "Ba"
  },
  {
    atomicMass: 138.905477,
    atomicRadius: "240",
    block: "f",
    boil: 3737,
    category: "lanthanide",
    density: 6.162,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 5d1",
    group: 3,
    melt: 1193,
    name: "Lanthanum",
    number: 57,
    oxidationStates: "+3",
    period: 6,
    phase: "Solid",
    symbol: "La"
  },
  {
    atomicMass: 140.1161,
    atomicRadius: "235",
    block: "f",
    boil: 3716,
    category: "lanthanide",
    density: 6.77,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 5d1 4f1",
    group: 3,
    melt: 1068,
    name: "Cerium",
    number: 58,
    oxidationStates: "+4, +3",
    period: 6,
    phase: "Solid",
    symbol: "Ce"
  },
  {
    atomicMass: 140.907662,
    atomicRadius: "239",
    block: "f",
    boil: 3403,
    category: "lanthanide",
    density: 6.77,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f3",
    group: 3,
    melt: 1208,
    name: "Praseodymium",
    number: 59,
    oxidationStates: "+3",
    period: 6,
    phase: "Solid",
    symbol: "Pr"
  },
  {
    atomicMass: 144.2423,
    atomicRadius: "229",
    block: "f",
    boil: 3347,
    category: "lanthanide",
    density: 7.01,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f4",
    group: 3,
    melt: 1297,
    name: "Neodymium",
    number: 60,
    oxidationStates: "+3",
    period: 6,
    phase: "Solid",
    symbol: "Nd"
  },
  {
    atomicMass: 145,
    atomicRadius: "236",
    block: "f",
    boil: 3273,
    category: "lanthanide",
    density: 7.26,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f5",
    group: 3,
    melt: 1315,
    name: "Promethium",
    number: 61,
    oxidationStates: "+3",
    period: 6,
    phase: "Solid",
    symbol: "Pm"
  },
  {
    atomicMass: 150.362,
    atomicRadius: "229",
    block: "f",
    boil: 2173,
    category: "lanthanide",
    density: 7.52,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f6",
    group: 3,
    melt: 1345,
    name: "Samarium",
    number: 62,
    oxidationStates: "+3, +2",
    period: 6,
    phase: "Solid",
    symbol: "Sm"
  },
  {
    atomicMass: 151.9641,
    atomicRadius: "233",
    block: "f",
    boil: 1802,
    category: "lanthanide",
    density: 5.264,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f7",
    group: 3,
    melt: 1099,
    name: "Europium",
    number: 63,
    oxidationStates: "+3, +2",
    period: 6,
    phase: "Solid",
    symbol: "Eu"
  },
  {
    atomicMass: 157.253,
    atomicRadius: "237",
    block: "f",
    boil: 3273,
    category: "lanthanide",
    density: 7.9,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f7 5d1",
    group: 3,
    melt: 1585,
    name: "Gadolinium",
    number: 64,
    oxidationStates: "+3",
    period: 6,
    phase: "Solid",
    symbol: "Gd"
  },
  {
    atomicMass: 158.925352,
    atomicRadius: "221",
    block: "f",
    boil: 3396,
    category: "lanthanide",
    density: 8.23,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f9",
    group: 3,
    melt: 1629,
    name: "Terbium",
    number: 65,
    oxidationStates: "+3",
    period: 6,
    phase: "Solid",
    symbol: "Tb"
  },
  {
    atomicMass: 162.5001,
    atomicRadius: "229",
    block: "f",
    boil: 2840,
    category: "lanthanide",
    density: 8.54,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f10",
    group: 3,
    melt: 1680,
    name: "Dysprosium",
    number: 66,
    oxidationStates: "+3",
    period: 6,
    phase: "Solid",
    symbol: "Dy"
  },
  {
    atomicMass: 164.930332,
    atomicRadius: "216",
    block: "f",
    boil: 2873,
    category: "lanthanide",
    density: 8.79,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f11",
    group: 3,
    melt: 1734,
    name: "Holmium",
    number: 67,
    oxidationStates: "+3",
    period: 6,
    phase: "Solid",
    symbol: "Ho"
  },
  {
    atomicMass: 167.2593,
    atomicRadius: "235",
    block: "f",
    boil: 3141,
    category: "lanthanide",
    density: 9.066,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f12",
    group: 3,
    melt: 1802,
    name: "Erbium",
    number: 68,
    oxidationStates: "+3",
    period: 6,
    phase: "Solid",
    symbol: "Er"
  },
  {
    atomicMass: 168.934222,
    atomicRadius: "227",
    block: "f",
    boil: 2223,
    category: "lanthanide",
    density: 9.32,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f13",
    group: 3,
    melt: 1818,
    name: "Thulium",
    number: 69,
    oxidationStates: "+3",
    period: 6,
    phase: "Solid",
    symbol: "Tm"
  },
  {
    atomicMass: 173.0451,
    atomicRadius: "242",
    block: "f",
    boil: 1469,
    category: "lanthanide",
    density: 6.9,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14",
    group: 3,
    melt: 1097,
    name: "Ytterbium",
    number: 70,
    oxidationStates: "+3, +2",
    period: 6,
    phase: "Solid",
    symbol: "Yb"
  },
  {
    atomicMass: 174.96681,
    atomicRadius: "221",
    block: "d",
    boil: 3675,
    category: "lanthanide",
    density: 9.841,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d1",
    group: 3,
    melt: 1925,
    name: "Lutetium",
    number: 71,
    oxidationStates: "+3",
    period: 6,
    phase: "Solid",
    symbol: "Lu"
  },
  {
    atomicMass: 178.492,
    atomicRadius: "212",
    block: "d",
    boil: 4876,
    category: "transition metal",
    density: 13.31,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d2",
    group: 4,
    melt: 2506,
    name: "Hafnium",
    number: 72,
    oxidationStates: "+4",
    period: 6,
    phase: "Solid",
    symbol: "Hf"
  },
  {
    atomicMass: 180.947882,
    atomicRadius: "217",
    block: "d",
    boil: 5731,
    category: "transition metal",
    density: 16.69,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d3",
    group: 5,
    melt: 3290,
    name: "Tantalum",
    number: 73,
    oxidationStates: "+5",
    period: 6,
    phase: "Solid",
    symbol: "Ta"
  },
  {
    atomicMass: 183.841,
    atomicRadius: "210",
    block: "d",
    boil: 6203,
    category: "transition metal",
    density: 19.25,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d4",
    group: 6,
    melt: 3695,
    name: "Tungsten",
    number: 74,
    oxidationStates: "+6",
    period: 6,
    phase: "Solid",
    symbol: "W"
  },
  {
    atomicMass: 186.2071,
    atomicRadius: "217",
    block: "d",
    boil: 5869,
    category: "transition metal",
    density: 21.02,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d5",
    group: 7,
    melt: 3459,
    name: "Rhenium",
    number: 75,
    oxidationStates: "+7, +6, +4",
    period: 6,
    phase: "Solid",
    symbol: "Re"
  },
  {
    atomicMass: 190.233,
    atomicRadius: "216",
    block: "d",
    boil: 5285,
    category: "transition metal",
    density: 22.59,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d6",
    group: 8,
    melt: 3306,
    name: "Osmium",
    number: 76,
    oxidationStates: "+4, +3",
    period: 6,
    phase: "Solid",
    symbol: "Os"
  },
  {
    atomicMass: 192.2173,
    atomicRadius: "202",
    block: "d",
    boil: 4403,
    category: "transition metal",
    density: 22.56,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d7",
    group: 9,
    melt: 2719,
    name: "Iridium",
    number: 77,
    oxidationStates: "+4, +3",
    period: 6,
    phase: "Solid",
    symbol: "Ir"
  },
  {
    atomicMass: 195.0849,
    atomicRadius: "209",
    block: "d",
    boil: 4098,
    category: "transition metal",
    density: 21.45,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s1 4f14 5d9",
    group: 10,
    melt: 2041.4,
    name: "Platinum",
    number: 78,
    oxidationStates: "+4, +2",
    period: 6,
    phase: "Solid",
    symbol: "Pt"
  },
  {
    atomicMass: 196.9665695,
    atomicRadius: "166",
    block: "d",
    boil: 3243,
    category: "transition metal",
    density: 19.3,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s1 4f14 5d10",
    group: 11,
    melt: 1337.33,
    name: "Gold",
    number: 79,
    oxidationStates: "+3, +1",
    period: 6,
    phase: "Solid",
    symbol: "Au"
  },
  {
    atomicMass: 200.5923,
    atomicRadius: "209",
    block: "d",
    boil: 629.88,
    category: "transition metal",
    density: 13.534,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10",
    group: 12,
    melt: 234.321,
    name: "Mercury",
    number: 80,
    oxidationStates: "+2, +1",
    period: 6,
    phase: "Liquid",
    symbol: "Hg"
  },
  {
    atomicMass: 204.38,
    atomicRadius: "196",
    block: "p",
    boil: 1746,
    category: "post-transition metal",
    density: 11.85,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p1",
    group: 13,
    melt: 577,
    name: "Thallium",
    number: 81,
    oxidationStates: "+3, +1",
    period: 6,
    phase: "Solid",
    symbol: "Tl"
  },
  {
    atomicMass: 207.21,
    atomicRadius: "202",
    block: "p",
    boil: 2022,
    category: "post-transition metal",
    density: 11.34,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p2",
    group: 14,
    melt: 600.61,
    name: "Lead",
    number: 82,
    oxidationStates: "+4, +2",
    period: 6,
    phase: "Solid",
    symbol: "Pb"
  },
  {
    atomicMass: 208.980401,
    atomicRadius: "207",
    block: "p",
    boil: 1837,
    category: "post-transition metal",
    density: 9.78,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p3",
    group: 15,
    melt: 544.7,
    name: "Bismuth",
    number: 83,
    oxidationStates: "+5, +3",
    period: 6,
    phase: "Solid",
    symbol: "Bi"
  },
  {
    atomicMass: 209,
    atomicRadius: "197",
    block: "p",
    boil: 1235,
    category: "post-transition metal",
    density: 9.196,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p4",
    group: 16,
    melt: 527,
    name: "Polonium",
    number: 84,
    oxidationStates: "+4, +2",
    period: 6,
    phase: "Solid",
    symbol: "Po"
  },
  {
    atomicMass: 210,
    atomicRadius: "202",
    block: "p",
    boil: 610,
    category: "metalloid",
    density: 6.35,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p5",
    group: 17,
    melt: 575,
    name: "Astatine",
    number: 85,
    oxidationStates: "7, 5, 3, 1, -1",
    period: 6,
    phase: "Solid",
    symbol: "At"
  },
  {
    atomicMass: 222,
    atomicRadius: "220",
    block: "p",
    boil: 211.5,
    category: "noble gas",
    density: 9.73,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6",
    group: 18,
    melt: 202,
    name: "Radon",
    number: 86,
    oxidationStates: "0",
    period: 6,
    phase: "Gas",
    symbol: "Rn"
  },
  {
    atomicMass: 223,
    atomicRadius: "348",
    block: "s",
    boil: 950,
    category: "alkali metal",
    density: 1.87,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s1",
    group: 1,
    melt: 300,
    name: "Francium",
    number: 87,
    oxidationStates: "+1",
    period: 7,
    phase: "Solid",
    symbol: "Fr"
  },
  {
    atomicMass: 226,
    atomicRadius: "283",
    block: "s",
    boil: 2010,
    category: "alkaline earth metal",
    density: 5.5,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2",
    group: 2,
    melt: 1233,
    name: "Radium",
    number: 88,
    oxidationStates: "+2",
    period: 7,
    phase: "Solid",
    symbol: "Ra"
  },
  {
    atomicMass: 227,
    atomicRadius: "260",
    block: "f",
    boil: 3500,
    category: "actinide",
    density: 10,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 6d1",
    group: 3,
    melt: 1500,
    name: "Actinium",
    number: 89,
    oxidationStates: "+3",
    period: 7,
    phase: "Solid",
    symbol: "Ac"
  },
  {
    atomicMass: 232.03774,
    atomicRadius: "237",
    block: "f",
    boil: 5061,
    category: "actinide",
    density: 11.724,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 6d2",
    group: 3,
    melt: 2023,
    name: "Thorium",
    number: 90,
    oxidationStates: "+4",
    period: 7,
    phase: "Solid",
    symbol: "Th"
  },
  {
    atomicMass: 231.035882,
    atomicRadius: "243",
    block: "f",
    boil: 4300,
    category: "actinide",
    density: 15.37,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f2 6d1",
    group: 3,
    melt: 1841,
    name: "Protactinium",
    number: 91,
    oxidationStates: "+5, +4",
    period: 7,
    phase: "Solid",
    symbol: "Pa"
  },
  {
    atomicMass: 238.028913,
    atomicRadius: "240",
    block: "f",
    boil: 4404,
    category: "actinide",
    density: 19.1,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f3 6d1",
    group: 3,
    melt: 1405.3,
    name: "Uranium",
    number: 92,
    oxidationStates: "+6, +5, +4, +3",
    period: 7,
    phase: "Solid",
    symbol: "U"
  },
  {
    atomicMass: 237,
    atomicRadius: "221",
    block: "f",
    boil: 4447,
    category: "actinide",
    density: 20.45,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f4 6d1",
    group: 3,
    melt: 912,
    name: "Neptunium",
    number: 93,
    oxidationStates: "+6, +5, +4, +3",
    period: 7,
    phase: "Solid",
    symbol: "Np"
  },
  {
    atomicMass: 244,
    atomicRadius: "243",
    block: "f",
    boil: 3505,
    category: "actinide",
    density: 19.816,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f6",
    group: 3,
    melt: 912.5,
    name: "Plutonium",
    number: 94,
    oxidationStates: "+6, +5, +4, +3",
    period: 7,
    phase: "Solid",
    symbol: "Pu"
  },
  {
    atomicMass: 243,
    atomicRadius: "244",
    block: "f",
    boil: 2880,
    category: "actinide",
    density: 12,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f7",
    group: 3,
    melt: 1449,
    name: "Americium",
    number: 95,
    oxidationStates: "+6, +5, +4, +3",
    period: 7,
    phase: "Solid",
    symbol: "Am"
  },
  {
    atomicMass: 247,
    atomicRadius: "245",
    block: "f",
    boil: 3383,
    category: "actinide",
    density: 13.51,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f7 6d1",
    group: 3,
    melt: 1613,
    name: "Curium",
    number: 96,
    oxidationStates: "+3",
    period: 7,
    phase: "Solid",
    symbol: "Cm"
  },
  {
    atomicMass: 247,
    atomicRadius: "244",
    block: "f",
    boil: 2900,
    category: "actinide",
    density: 14.78,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f9",
    group: 3,
    melt: 1259,
    name: "Berkelium",
    number: 97,
    oxidationStates: "+4, +3",
    period: 7,
    phase: "Solid",
    symbol: "Bk"
  },
  {
    atomicMass: 251,
    atomicRadius: "245",
    block: "f",
    boil: 1743,
    category: "actinide",
    density: 15.1,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f10",
    group: 3,
    melt: 1173,
    name: "Californium",
    number: 98,
    oxidationStates: "+3",
    period: 7,
    phase: "Solid",
    symbol: "Cf"
  },
  {
    atomicMass: 252,
    atomicRadius: "245",
    block: "f",
    boil: 1269,
    category: "actinide",
    density: 8.84,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f11",
    group: 3,
    melt: 1133,
    name: "Einsteinium",
    number: 99,
    oxidationStates: "+3",
    period: 7,
    phase: "Solid",
    symbol: "Es"
  },
  {
    atomicMass: 257,
    atomicRadius: "",
    block: "f",
    boil: 1269,
    category: "actinide",
    density: 8.84,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f12",
    group: 3,
    melt: 1800,
    name: "Fermium",
    number: 100,
    oxidationStates: "+3",
    period: 7,
    phase: "Solid",
    symbol: "Fm"
  },
  {
    atomicMass: 258,
    atomicRadius: "",
    block: "f",
    boil: 1269,
    category: "actinide",
    density: 8.84,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f13",
    group: 3,
    melt: 1100,
    name: "Mendelevium",
    number: 101,
    oxidationStates: "+3, +2",
    period: 7,
    phase: "Solid",
    symbol: "Md"
  },
  {
    atomicMass: 259,
    atomicRadius: "",
    block: "f",
    boil: 1269,
    category: "actinide",
    density: 8.84,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f14",
    group: 3,
    melt: 1100,
    name: "Nobelium",
    number: 102,
    oxidationStates: "+3, +2",
    period: 7,
    phase: "Solid",
    symbol: "No"
  },
  {
    atomicMass: 266,
    atomicRadius: "",
    block: "d",
    boil: 1269,
    category: "actinide",
    density: 8.84,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f14 7p1",
    group: 3,
    melt: 1900,
    name: "Lawrencium",
    number: 103,
    oxidationStates: "+3",
    period: 7,
    phase: "Solid",
    symbol: "Lr"
  },
  {
    atomicMass: 267,
    atomicRadius: "",
    block: "d",
    boil: 5800,
    category: "transition metal",
    density: 23.2,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f14 6d2",
    group: 4,
    melt: 2400,
    name: "Rutherfordium",
    number: 104,
    oxidationStates: "+4",
    period: 7,
    phase: "Solid",
    symbol: "Rf"
  },
  {
    atomicMass: 268,
    atomicRadius: "",
    block: "d",
    boil: 5800,
    category: "transition metal",
    density: 29.3,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f14 6d3",
    group: 5,
    melt: 2400,
    name: "Dubnium",
    number: 105,
    oxidationStates: "5, 4, 3",
    period: 7,
    phase: "Solid",
    symbol: "Db"
  },
  {
    atomicMass: 269,
    atomicRadius: "",
    block: "d",
    boil: 5800,
    category: "transition metal",
    density: 35,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f14 6d4",
    group: 6,
    melt: 2400,
    name: "Seaborgium",
    number: 106,
    oxidationStates: "6, 5, 4, 3, 0",
    period: 7,
    phase: "Solid",
    symbol: "Sg"
  },
  {
    atomicMass: 270,
    atomicRadius: "",
    block: "d",
    boil: 5800,
    category: "transition metal",
    density: 37.1,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f14 6d5",
    group: 7,
    melt: 2400,
    name: "Bohrium",
    number: 107,
    oxidationStates: "7, 5, 4, 3",
    period: 7,
    phase: "Solid",
    symbol: "Bh"
  },
  {
    atomicMass: 269,
    atomicRadius: "",
    block: "d",
    boil: 5800,
    category: "transition metal",
    density: 40.7,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f14 6d6",
    group: 8,
    melt: 126,
    name: "Hassium",
    number: 108,
    oxidationStates: "8, 6, 5, 4, 3, 2",
    period: 7,
    phase: "Solid",
    symbol: "Hs"
  },
  {
    atomicMass: 278,
    atomicRadius: "",
    block: "d",
    boil: 5800,
    category: "unknown, probably transition metal",
    density: 37.4,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f14 6d7",
    group: 9,
    melt: 126,
    name: "Meitnerium",
    number: 109,
    oxidationStates: "9, 8, 6, 4, 3, 1",
    period: 7,
    phase: "Solid",
    symbol: "Mt"
  },
  {
    atomicMass: 281,
    atomicRadius: "",
    block: "d",
    boil: 5800,
    category: "unknown, probably transition metal",
    density: 34.8,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f14 6d8",
    group: 10,
    melt: 126,
    name: "Darmstadtium",
    number: 110,
    oxidationStates: "8, 6, 4, 2, 0",
    period: 7,
    phase: "Solid",
    symbol: "Ds"
  },
  {
    atomicMass: 282,
    atomicRadius: "",
    block: "d",
    boil: 5800,
    category: "unknown, probably transition metal",
    density: 28.7,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f14 6d9",
    group: 11,
    melt: 126,
    name: "Roentgenium",
    number: 111,
    oxidationStates: "5, 3, 1, -1",
    period: 7,
    phase: "Solid",
    symbol: "Rg"
  },
  {
    atomicMass: 285,
    atomicRadius: "",
    block: "d",
    boil: 3570,
    category: "transition metal",
    density: 14,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f14 6d10",
    group: 12,
    melt: 126,
    name: "Copernicium",
    number: 112,
    oxidationStates: "2, 1, 0",
    period: 7,
    phase: "Liquid",
    symbol: "Cn"
  },
  {
    atomicMass: 286,
    atomicRadius: "",
    block: "p",
    boil: 1430,
    category: "unknown, probably transition metal",
    density: 16,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f14 6d10 7p1",
    group: 13,
    melt: 700,
    name: "Nihonium",
    number: 113,
    oxidationStates: "",
    period: 7,
    phase: "Solid",
    symbol: "Nh"
  },
  {
    atomicMass: 289,
    atomicRadius: "",
    block: "p",
    boil: 420,
    category: "post-transition metal",
    density: 14,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f14 6d10 7p2",
    group: 14,
    melt: 340,
    name: "Flerovium",
    number: 114,
    oxidationStates: "6, 4,2, 1, 0",
    period: 7,
    phase: "Solid",
    symbol: "Fl"
  },
  {
    atomicMass: 289,
    atomicRadius: "",
    block: "p",
    boil: 1400,
    category: "unknown, probably post-transition metal",
    density: 13.5,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f14 6d10 7p3",
    group: 15,
    melt: 670,
    name: "Moscovium",
    number: 115,
    oxidationStates: "3, 1",
    period: 7,
    phase: "Solid",
    symbol: "Mc"
  },
  {
    atomicMass: 293,
    atomicRadius: "",
    block: "p",
    boil: 1085,
    category: "unknown, probably post-transition metal",
    density: 12.9,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f14 6d10 7p4",
    group: 16,
    melt: 709,
    name: "Livermorium",
    number: 116,
    oxidationStates: "+4, +2, -2",
    period: 7,
    phase: "Solid",
    symbol: "Lv"
  },
  {
    atomicMass: 294,
    atomicRadius: "",
    block: "p",
    boil: 883,
    category: "unknown, probably metalloid",
    density: 7.17,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f14 6d10 7p5",
    group: 17,
    melt: 723,
    name: "Tennessine",
    number: 117,
    oxidationStates: "+5, +3, +1, -1",
    period: 7,
    phase: "Solid",
    symbol: "Ts"
  },
  {
    atomicMass: 294,
    atomicRadius: "",
    block: "p",
    boil: 350,
    category: "unknown, predicted to be noble gas",
    density: 4.95,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f14 6d10 7p6",
    group: 18,
    melt: 723,
    name: "Oganesson",
    number: 118,
    oxidationStates: "+6, +4, +2, +1, 0, -1",
    period: 7,
    phase: "Solid",
    symbol: "Og"
  },
  {
    atomicMass: 315,
    atomicRadius: "",
    block: "s",
    boil: 630,
    category: "unknown, but predicted to be an alkali metal",
    density: 3,
    electronConfig: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f14 6d10 7p6 8s1",
    group: 1,
    melt: 723,
    name: "Ununennium",
    number: 119,
    oxidationStates: "",
    period: 8,
    phase: "Solid",
    symbol: "Uue"
  }
];

// node_modules/fitty/dist/fitty.module.js
var e = function(e2) {
  if (e2) {
    var t = function(e3) {
      return [].slice.call(e3);
    }, n = 0, i = 1, r = 2, o = 3, a = [], l = null, u = "requestAnimationFrame" in e2 ? function() {
      e2.cancelAnimationFrame(l), l = e2.requestAnimationFrame(function() {
        return s(a.filter(function(e3) {
          return e3.dirty && e3.active;
        }));
      });
    } : function() {
    }, c = function(e3) {
      return function() {
        a.forEach(function(t2) {
          return t2.dirty = e3;
        }), u();
      };
    }, s = function(e3) {
      e3.filter(function(e4) {
        return !e4.styleComputed;
      }).forEach(function(e4) {
        e4.styleComputed = m(e4);
      }), e3.filter(y).forEach(v);
      var t2 = e3.filter(p);
      t2.forEach(d), t2.forEach(function(e4) {
        v(e4), f(e4);
      }), t2.forEach(S);
    }, f = function(e3) {
      return e3.dirty = n;
    }, d = function(e3) {
      e3.availableWidth = e3.element.parentNode.clientWidth, e3.currentWidth = e3.element.scrollWidth, e3.previousFontSize = e3.currentFontSize, e3.currentFontSize = Math.min(Math.max(e3.minSize, e3.availableWidth / e3.currentWidth * e3.previousFontSize), e3.maxSize), e3.whiteSpace = e3.multiLine && e3.currentFontSize === e3.minSize ? "normal" : "nowrap";
    }, p = function(e3) {
      return e3.dirty !== r || e3.dirty === r && e3.element.parentNode.clientWidth !== e3.availableWidth;
    }, m = function(t2) {
      var n2 = e2.getComputedStyle(t2.element, null);
      return t2.currentFontSize = parseFloat(n2.getPropertyValue("font-size")), t2.display = n2.getPropertyValue("display"), t2.whiteSpace = n2.getPropertyValue("white-space"), true;
    }, y = function(e3) {
      var t2 = false;
      return !e3.preStyleTestCompleted && (/inline-/.test(e3.display) || (t2 = true, e3.display = "inline-block"), "nowrap" !== e3.whiteSpace && (t2 = true, e3.whiteSpace = "nowrap"), e3.preStyleTestCompleted = true, t2);
    }, v = function(e3) {
      e3.element.style.whiteSpace = e3.whiteSpace, e3.element.style.display = e3.display, e3.element.style.fontSize = e3.currentFontSize + "px";
    }, S = function(e3) {
      e3.element.dispatchEvent(new CustomEvent("fit", { detail: { oldValue: e3.previousFontSize, newValue: e3.currentFontSize, scaleFactor: e3.currentFontSize / e3.previousFontSize } }));
    }, h = function(e3, t2) {
      return function() {
        e3.dirty = t2, e3.active && u();
      };
    }, w = function(e3) {
      return function() {
        a = a.filter(function(t2) {
          return t2.element !== e3.element;
        }), e3.observeMutations && e3.observer.disconnect(), e3.element.style.whiteSpace = e3.originalStyle.whiteSpace, e3.element.style.display = e3.originalStyle.display, e3.element.style.fontSize = e3.originalStyle.fontSize;
      };
    }, b = function(e3) {
      return function() {
        e3.active || (e3.active = true, u());
      };
    }, z = function(e3) {
      return function() {
        return e3.active = false;
      };
    }, F = function(e3) {
      e3.observeMutations && (e3.observer = new MutationObserver(h(e3, i)), e3.observer.observe(e3.element, e3.observeMutations));
    }, g = { minSize: 16, maxSize: 512, multiLine: true, observeMutations: "MutationObserver" in e2 && { subtree: true, childList: true, characterData: true } }, W = null, E = function() {
      e2.clearTimeout(W), W = e2.setTimeout(c(r), x.observeWindowDelay);
    }, M = ["resize", "orientationchange"];
    return Object.defineProperty(x, "observeWindow", { set: function(t2) {
      var n2 = "".concat(t2 ? "add" : "remove", "EventListener");
      M.forEach(function(t3) {
        e2[n2](t3, E);
      });
    } }), x.observeWindow = true, x.observeWindowDelay = 100, x.fitAll = c(o), x;
  }
  function C(e3, t2) {
    var n2 = Object.assign({}, g, t2), i2 = e3.map(function(e4) {
      var t3 = Object.assign({}, n2, { element: e4, active: true });
      return function(e5) {
        e5.originalStyle = { whiteSpace: e5.element.style.whiteSpace, display: e5.element.style.display, fontSize: e5.element.style.fontSize }, F(e5), e5.newbie = true, e5.dirty = true, a.push(e5);
      }(t3), { element: e4, fit: h(t3, o), unfreeze: b(t3), freeze: z(t3), unsubscribe: w(t3) };
    });
    return u(), i2;
  }
  function x(e3) {
    var n2 = arguments.length > 1 && void 0 !== arguments[1] ? arguments[1] : {};
    return "string" == typeof e3 ? C(t(document.querySelectorAll(e3)), n2) : C([e3], n2)[0];
  }
}("undefined" == typeof window ? null : window);
var fitty_module_default = e;

// main.ts
var PERIODIC_VIEW = "periodic-view";
var MyPlugin = class extends import_obsidian.Plugin {
  onload() {
    const infoView = this.app.workspace.getLeavesOfType(PERIODIC_VIEW)[0];
    if (!infoView) {
      this.registerView(
        PERIODIC_VIEW,
        (leaf) => new PeriodicView(leaf)
      );
    }
    this.activateView();
  }
  onunload() {
  }
  async activateView() {
    await this.app.workspace.getRightLeaf(false).setViewState({
      type: PERIODIC_VIEW,
      active: false
    });
  }
};
var PeriodicView = class _PeriodicView extends import_obsidian.ItemView {
  constructor(leaf) {
    super(leaf);
  }
  getViewType() {
    return PERIODIC_VIEW;
  }
  getDisplayText() {
    return "Periodic table";
  }
  async onOpen() {
    this.containerEl.empty();
    this.containerEl.createDiv(
      { cls: "mainDiv" },
      (div) => {
        for (let i = 0; i < 9; i++) {
          div.createDiv(
            { cls: "subDiv" },
            (div2) => {
              for (let j = 0; j < 18; j++) {
                const num = this.setElementData(i * 18 + j);
                const tempDiv = div2.createDiv(
                  { cls: "element", attr: { id: _PeriodicView.setElementDataToString(num) } },
                  (div3) => {
                    div3.createEl("p", { text: num.toString(), cls: "numOfEl" });
                    if (num > -1) {
                      div3.createEl("p", { text: periodicTable_default[num - 1].symbol, cls: "elSymb" });
                    }
                  }
                );
                tempDiv.addEventListener("click", function() {
                  const element = periodicTable_default[num - 1];
                  dataDiv.children[0].id = _PeriodicView.setElementDataToString(num);
                  dataDiv.children[0].children[0].children[0].textContent = element.number.toString();
                  dataDiv.children[0].children[0].children[1].textContent = element.atomicMass.toString().substring(0, 10);
                  dataDiv.children[0].children[1].textContent = element.symbol;
                  dataDiv.children[0].children[2].textContent = element.name;
                  fitty_module_default("#name");
                  dataDiv.children[1].textContent = "Category: " + element.category;
                  dataDiv.children[2].textContent = "Electron configuration: \n" + element.electronConfig;
                  dataDiv.children[3].textContent = "Group: " + element.group.toString();
                  dataDiv.children[4].textContent = "Period: " + element.period.toString();
                  dataDiv.children[5].textContent = "Number of valence electrons: " + _PeriodicView.findValenceElectrons(num).toString();
                  dataDiv.children[6].textContent = "Oxidation states: " + element.oxidationStates;
                  dataDiv.children[7].textContent = "Atomic radius: " + element.atomicRadius;
                  dataDiv.children[8].textContent = "Phase: " + element.phase;
                });
              }
            }
          );
        }
      }
    );
    const dataDiv = createDiv(
      { cls: "dataDiv" },
      (div) => {
        div.createDiv(
          { cls: "bigElement" },
          (div2) => {
            div2.createDiv({ cls: "numberAndMass" }, (div3) => {
              div3.createEl("p", { cls: "number" });
              div3.createEl("p", { cls: "mass" });
            });
            div2.createEl("h1", { cls: "symbol" });
            div2.createEl("div", { cls: "name" });
          }
        );
        div.createEl("div", { cls: "category attrib" });
        div.createEl("div", { cls: "electron-config attrib" });
        div.createEl("div", { cls: "group attrib" });
        div.createEl("div", { cls: "period attrib" });
        div.createEl("div", { cls: "valence attrib" });
        div.createEl("div", { cls: "oxidationStates attrib" });
        div.createEl("div", { cls: "atomicRadius attrib" });
        div.createEl("div", { cls: "phase attrib" });
      }
    );
    this.containerEl.appendChild(dataDiv);
  }
  setElementData(num) {
    if (num == 0)
      return 1;
    if (num > 0 && num < 17)
      return -1;
    num -= 15;
    if (num <= 4)
      return num;
    if (num > 4 && num < 15)
      return -1;
    num -= 10;
    if (num <= 12)
      return num;
    if (num > 12 && num < 23)
      return -1;
    num -= 10;
    if (num > 57)
      num += 14;
    if (num > 89)
      num += 14;
    if (num > 118 && num < 121)
      return -1;
    if (num > 134 && num < 139)
      return -1;
    if (num > 152)
      return -1;
    if (num > 137)
      num += 14;
    if (num > 118)
      num -= 63;
    return num;
  }
  static setElementDataToString(num) {
    if (num == -1)
      return "nonExistant";
    num = num - 1;
    let str = periodicTable_default[num].category;
    if (str == "polyatomic nonmetal")
      str = "nonmetal";
    else if (str == "diatomic nonmetal")
      str = "nonmetal";
    else if (str == "noble gas")
      str = "noble-gas";
    else if (str == "alkali metal")
      str = "alkali-metal";
    else if (str == "alkaline earth metal")
      str = "alkaline-earth-metal";
    else if (str == "post-transition metal")
      str = "post-transition-metal";
    else if (str == "transition metal")
      str = "transition-metal";
    else if (str.startsWith("unknown"))
      str = "unknown";
    return str;
  }
  static findValenceElectrons(num) {
    num -= 1;
    const group = periodicTable_default[num].group;
    if (group < 3)
      return group;
    if (group > 12)
      return group % 10;
    const electronConfigString = periodicTable_default[num].electronConfig;
    const electronConfigArr = electronConfigString.split(" ");
    let maxOrbit = 0;
    for (let i = 0; i < electronConfigArr.length; i++) {
      if (parseInt(electronConfigArr[i].charAt(0)) > maxOrbit) {
        maxOrbit = i;
      }
    }
    return parseInt(electronConfigArr[maxOrbit].charAt(2));
  }
  async onClose() {
    this.unload();
  }
};


/* nosourcemap */